'use client';

import * as React from 'react';
import { Alert, Box, Button, Card, CardContent, Checkbox, Chip, Dialog, DialogActions, DialogContent, DialogTitle, FormControl, IconButton, InputAdornment, InputLabel, MenuItem, Pagination, Select, Skeleton, Snackbar, Stack, Switch, Table, TableBody, TableCell, TableContainer, TableHead, TableRow, TextField, Tooltip, Typography } from '@mui/material';
import AddRoundedIcon from '@mui/icons-material/AddRounded';
import CategoryRoundedIcon from '@mui/icons-material/CategoryRounded';
import DeleteOutlineRoundedIcon from '@mui/icons-material/DeleteOutlineRounded';
import DragIndicatorRoundedIcon from '@mui/icons-material/DragIndicatorRounded';
import EditRoundedIcon from '@mui/icons-material/EditRounded';
import Inventory2OutlinedIcon from '@mui/icons-material/Inventory2Outlined';
import PowerSettingsNewRoundedIcon from '@mui/icons-material/PowerSettingsNewRounded';
import RefreshRoundedIcon from '@mui/icons-material/RefreshRounded';
import SearchRoundedIcon from '@mui/icons-material/SearchRounded';
import AdminPageContainer from '../../components/AdminPageContainer';
import { commonButtonSx, tableShellSx, uiCardSx } from '../../components/adminUi';
import type { Product } from '@/lib/contracts';
import { createQuickProduct, deleteQuickProduct, fetchQuickProductsForAdmin, updateQuickProduct, type QuickProductPayload } from '@/lib/products';
import InlinePriceEditor from './components/InlinePriceEditor';
import QuickSellerEditor from './components/QuickSellerEditor';

const ALL = 'ทั้งหมด';
const EMPTY: QuickProductPayload = { name: '', code: '', category: 'ทั่วไป', price: 0, unitLabel: 'ชิ้น', emoji: '📄', tint: '#E2E8F0', active: true, isHotMenu: false, quickSaleSortOrder: 0 };
type Sort = 'order' | 'name' | 'updated';
const pageSizes = [10, 25, 50, 100];
const formatDate = (value?: string) => value ? new Date(value).toLocaleString('th-TH', { dateStyle: 'medium', timeStyle: 'short' }) : '—';
const toPayload = (p: Product): QuickProductPayload => ({ name: p.name, code: p.code, typeCode: p.typeCode, category: p.category, price: p.variants[0]?.price ?? 0, unitLabel: p.unitLabel, emoji: p.emoji, tint: p.tint, isHotMenu: p.isHotMenu, active: p.active, quickSaleSortOrder: p.quickSaleSortOrder ?? 0 });

export default function QuickMenuSettingsPage() {
  const [products, setProducts] = React.useState<Product[]>([]);
  const [query, setQuery] = React.useState(''); const [category, setCategory] = React.useState(ALL); const [status, setStatus] = React.useState(ALL); const [sort, setSort] = React.useState<Sort>('order');
  const [page, setPage] = React.useState(1); const [rowsPerPage, setRowsPerPage] = React.useState(10); const [selected, setSelected] = React.useState<string[]>([]);
  const [loading, setLoading] = React.useState(true); const [error, setError] = React.useState<string | null>(null); const [notice, setNotice] = React.useState<string | null>(null); const [pending, setPending] = React.useState<string[]>([]);
  const [editing, setEditing] = React.useState<Product | null>(null); const [draft, setDraft] = React.useState<QuickProductPayload>(EMPTY); const [editorOpen, setEditorOpen] = React.useState(false); const [deleteTarget, setDeleteTarget] = React.useState<Product | null>(null);
  const busy = pending.length > 0;
  const load = React.useCallback(async () => { setLoading(true); setError(null); try { setProducts(await fetchQuickProductsForAdmin()); } catch (e) { setError(e instanceof Error ? e.message : 'โหลดรายการขายด่วนไม่สำเร็จ'); } finally { setLoading(false); } }, []);
  React.useEffect(() => { void load(); }, [load]);
  React.useEffect(() => setPage(1), [query, category, status, sort, rowsPerPage]);
  const categories = React.useMemo(() => [ALL, ...Array.from(new Set(products.map(p => p.category))).sort((a, b) => a.localeCompare(b, 'th'))], [products]);
  const visible = React.useMemo(() => products.filter(p => `${p.name} ${p.code} ${p.category}`.toLowerCase().includes(query.trim().toLowerCase())).filter(p => category === ALL || p.category === category).filter(p => status === ALL || (status === 'active' ? p.active : !p.active)).sort((a, b) => sort === 'name' ? a.name.localeCompare(b.name, 'th') : sort === 'updated' ? (b.updatedAt || '').localeCompare(a.updatedAt || '') : (a.quickSaleSortOrder ?? 0) - (b.quickSaleSortOrder ?? 0)), [products, query, category, status, sort]);
  const paged = visible.slice((page - 1) * rowsPerPage, page * rowsPerPage); const pageCount = Math.max(1, Math.ceil(visible.length / rowsPerPage));
  const patchRow = async (product: Product, patch: Partial<QuickProductPayload>, message: string) => { if (pending.includes(product.id)) return; setPending(ids => [...ids, product.id]); setError(null); try { const updated = await updateQuickProduct(product.id, patch); setProducts(items => items.map(item => item.id === product.id ? updated : item)); setNotice(message); } catch (e) { setError(e instanceof Error ? e.message : 'อัปเดตรายการไม่สำเร็จ'); throw e; } finally { setPending(ids => ids.filter(id => id !== product.id)); } };
  const openEditor = (product: Product | null) => { setEditing(product); setDraft(product ? toPayload(product) : EMPTY); setEditorOpen(true); };
  const saveEditor = async (value: QuickProductPayload) => { const id = editing?.id ?? 'new'; setPending(ids => [...ids, id]); try { const saved = editing ? await updateQuickProduct(editing.id, value) : await createQuickProduct(value); setProducts(items => editing ? items.map(item => item.id === editing.id ? saved : item) : [...items, saved]); setEditorOpen(false); setNotice(editing ? 'บันทึกการแก้ไขแล้ว' : 'เพิ่มรายการขายด่วนแล้ว'); } finally { setPending(ids => ids.filter(item => item !== id)); } };
  const remove = async () => { if (!deleteTarget) return; const target = deleteTarget; setPending(ids => [...ids, target.id]); try { await deleteQuickProduct(target.id); setProducts(items => items.filter(item => item.id !== target.id)); setDeleteTarget(null); setNotice('ลบรายการแล้ว'); } catch (e) { setError(e instanceof Error ? e.message : 'ลบรายการไม่สำเร็จ'); } finally { setPending(ids => ids.filter(id => id !== target.id)); } };
  const allOnPage = paged.length > 0 && paged.every(p => selected.includes(p.id));

  return <AdminPageContainer><Stack spacing={2}>
    <Stack direction={{ xs: 'column', md: 'row' }} justifyContent="space-between" alignItems={{ xs: 'stretch', md: 'flex-start' }} gap={2}>
      <Box><Typography variant="h4" fontWeight={850} color="#101828">จัดการการขายด่วน</Typography><Typography color="text.secondary" sx={{ mt: .5 }}>จัดการรายการสินค้า ราคาหน้าร้าน และลำดับการแสดงผลในหน้าขายด่วน</Typography></Box>
      <Stack direction="row" gap={1}><Button variant="outlined" startIcon={<RefreshRoundedIcon />} onClick={() => void load()} disabled={loading} sx={commonButtonSx}>รีเฟรช</Button><Button variant="contained" startIcon={<AddRoundedIcon />} onClick={() => openEditor(null)} sx={commonButtonSx}>เพิ่มรายการใหม่</Button></Stack>
    </Stack>
    {error && <Alert severity="error" action={<Button color="inherit" size="small" onClick={() => void load()}>ลองใหม่</Button>} onClose={() => setError(null)}>{error}</Alert>}
    <Box sx={{ display: 'grid', gridTemplateColumns: { xs: 'repeat(2, 1fr)', lg: 'repeat(4, 1fr)' }, gap: 1.25 }}>
      {[{ label: 'รายการทั้งหมด', value: products.length, icon: <Inventory2OutlinedIcon />, color: '#2563EB' }, { label: 'กำลังใช้งาน', value: products.filter(p => p.active).length, icon: <PowerSettingsNewRoundedIcon />, color: '#16A34A' }, { label: 'ปิดใช้งาน', value: products.filter(p => !p.active).length, icon: <PowerSettingsNewRoundedIcon />, color: '#64748B' }, { label: 'หมวดหมู่', value: Math.max(0, categories.length - 1), icon: <CategoryRoundedIcon />, color: '#7C3AED' }].map(item => <Card key={item.label} sx={uiCardSx}><CardContent sx={{ p: '14px !important', display: 'flex', alignItems: 'center', gap: 1.5 }}><Box sx={{ width: 38, height: 38, borderRadius: 2, display: 'grid', placeItems: 'center', color: item.color, bgcolor: `${item.color}12` }}>{item.icon}</Box><Box><Typography variant="caption" color="text.secondary">{item.label}</Typography><Typography variant="h5" fontWeight={850} lineHeight={1.1}>{item.value}</Typography></Box></CardContent></Card>)}
    </Box>
    <Card sx={uiCardSx}><CardContent sx={{ p: '14px !important' }}><Box sx={{ display: 'grid', gridTemplateColumns: { xs: '1fr', md: 'minmax(260px, 1fr) repeat(3, minmax(145px, .32fr))' }, gap: 1.25 }}>
      <TextField size="small" placeholder="ค้นหาชื่อสินค้า / รหัสสินค้า" value={query} onChange={e => setQuery(e.target.value)} InputProps={{ startAdornment: <InputAdornment position="start"><SearchRoundedIcon fontSize="small" /></InputAdornment> }} />
      <FormControl size="small"><InputLabel>หมวดหมู่</InputLabel><Select label="หมวดหมู่" value={category} onChange={e => setCategory(e.target.value)}>{categories.map(c => <MenuItem key={c} value={c}>{c}</MenuItem>)}</Select></FormControl>
      <FormControl size="small"><InputLabel>สถานะ</InputLabel><Select label="สถานะ" value={status} onChange={e => setStatus(e.target.value)}><MenuItem value={ALL}>ทั้งหมด</MenuItem><MenuItem value="active">ใช้งาน</MenuItem><MenuItem value="inactive">ปิดใช้งาน</MenuItem></Select></FormControl>
      <FormControl size="small"><InputLabel>เรียงตาม</InputLabel><Select label="เรียงตาม" value={sort} onChange={e => setSort(e.target.value as Sort)}><MenuItem value="order">ลำดับแสดงผล</MenuItem><MenuItem value="name">ชื่อสินค้า</MenuItem><MenuItem value="updated">อัปเดตล่าสุด</MenuItem></Select></FormControl>
    </Box><Stack direction="row" gap={.75} sx={{ mt: 1.25, overflowX: 'auto', pb: .25 }}>{categories.map(c => <Chip key={c} label={c} clickable color={category === c ? 'primary' : 'default'} variant={category === c ? 'filled' : 'outlined'} onClick={() => setCategory(c)} sx={{ flexShrink: 0, fontWeight: category === c ? 700 : 500 }} />)}</Stack></CardContent></Card>
    {selected.length > 0 && <Alert severity="info" icon={false}><Stack direction={{ xs: 'column', sm: 'row' }} justifyContent="space-between" alignItems={{ sm: 'center' }} gap={1}><Typography fontWeight={700}>เลือกแล้ว {selected.length} รายการ</Typography><Button size="small" onClick={() => setSelected([])}>ยกเลิกการเลือก</Button></Stack></Alert>}
    <Card sx={{ ...uiCardSx, overflow: 'hidden' }}>
      <TableContainer sx={{ display: { xs: 'none', md: 'block' } }}><Table size="small" sx={tableShellSx}><TableHead><TableRow><TableCell padding="checkbox"><Checkbox checked={allOnPage} indeterminate={selected.length > 0 && !allOnPage} onChange={e => setSelected(e.target.checked ? Array.from(new Set([...selected, ...paged.map(p => p.id)])) : selected.filter(id => !paged.some(p => p.id === id)))} /></TableCell><TableCell sx={{ width: 38 }} /><TableCell>สินค้า</TableCell><TableCell>หมวดหมู่</TableCell><TableCell>ราคา</TableCell><TableCell align="center">ลำดับ</TableCell><TableCell>สถานะ</TableCell><TableCell>อัปเดตล่าสุด</TableCell><TableCell align="right">จัดการ</TableCell></TableRow></TableHead>
      <TableBody>{loading ? Array.from({ length: 7 }, (_, i) => <TableRow key={i}><TableCell colSpan={9}><Skeleton height={38} /></TableCell></TableRow>) : paged.map(p => <TableRow key={p.id} hover sx={{ opacity: p.active ? 1 : .62 }}><TableCell padding="checkbox"><Checkbox checked={selected.includes(p.id)} onChange={e => setSelected(ids => e.target.checked ? [...ids, p.id] : ids.filter(id => id !== p.id))} /></TableCell><TableCell><DragIndicatorRoundedIcon color="disabled" fontSize="small" /></TableCell><TableCell><Stack direction="row" alignItems="center" gap={1}><Box sx={{ width: 36, height: 36, borderRadius: 1.5, bgcolor: p.tint || '#EEF2F6', display: 'grid', placeItems: 'center', fontSize: 20 }}>{p.emoji || '📄'}</Box><Box><Typography fontWeight={750} fontSize={14}>{p.name}</Typography><Typography variant="caption" color="text.secondary">{p.code}</Typography></Box></Stack></TableCell><TableCell><Chip size="small" label={p.category} variant="outlined" /></TableCell><TableCell><InlinePriceEditor value={p.variants[0]?.price ?? 0} disabled={pending.includes(p.id)} onSave={price => patchRow(p, { price }, 'อัปเดตราคาแล้ว')} /></TableCell><TableCell align="center"><TextField size="small" type="number" defaultValue={p.quickSaleSortOrder ?? 0} inputProps={{ min: 0, 'aria-label': `ลำดับ ${p.name}` }} onBlur={e => { const next = Math.max(0, Number(e.target.value) || 0); if (next !== (p.quickSaleSortOrder ?? 0)) void patchRow(p, { quickSaleSortOrder: next }, 'อัปเดตลำดับแล้ว'); }} sx={{ width: 66, '& input': { py: .65, textAlign: 'center' } }} /></TableCell><TableCell><Stack direction="row" alignItems="center"><Switch size="small" checked={p.active} disabled={pending.includes(p.id)} onChange={() => void patchRow(p, { active: !p.active }, p.active ? 'ปิดใช้งานแล้ว' : 'เปิดใช้งานแล้ว')} /><Typography variant="caption" fontWeight={700} color={p.active ? 'success.main' : 'text.secondary'}>{p.active ? 'ใช้งาน' : 'ปิด'}</Typography></Stack></TableCell><TableCell><Typography variant="caption">{formatDate(p.updatedAt)}</Typography></TableCell><TableCell align="right"><Tooltip title="แก้ไข"><IconButton size="small" onClick={() => openEditor(p)}><EditRoundedIcon fontSize="small" /></IconButton></Tooltip><Tooltip title="ลบ"><IconButton size="small" color="error" onClick={() => setDeleteTarget(p)}><DeleteOutlineRoundedIcon fontSize="small" /></IconButton></Tooltip></TableCell></TableRow>)}</TableBody></Table></TableContainer>
      <Stack sx={{ display: { md: 'none' }, p: 1.25 }} spacing={1}>{loading ? Array.from({ length: 4 }, (_, i) => <Skeleton key={i} variant="rounded" height={190} />) : paged.map(p => <Card key={p.id} variant="outlined"><CardContent sx={{ p: '14px !important' }}><Stack direction="row" alignItems="flex-start" gap={1}><Box sx={{ width: 42, height: 42, borderRadius: 1.5, bgcolor: p.tint || '#EEF2F6', display: 'grid', placeItems: 'center', fontSize: 22 }}>{p.emoji || '📄'}</Box><Box flex={1} minWidth={0}><Typography fontWeight={800}>{p.name}</Typography><Typography variant="caption" color="text.secondary">{p.code} · {p.category}</Typography></Box><IconButton size="small" onClick={() => openEditor(p)}><EditRoundedIcon fontSize="small" /></IconButton></Stack><Stack direction="row" alignItems="center" justifyContent="space-between" sx={{ mt: 1.5 }}><InlinePriceEditor value={p.variants[0]?.price ?? 0} disabled={pending.includes(p.id)} onSave={price => patchRow(p, { price }, 'อัปเดตราคาแล้ว')} /><Switch checked={p.active} onChange={() => void patchRow(p, { active: !p.active }, 'อัปเดตสถานะแล้ว')} /></Stack><Typography variant="caption" color="text.secondary">ลำดับ {p.quickSaleSortOrder ?? 0} · {formatDate(p.updatedAt)}</Typography></CardContent></Card>)}</Stack>
      {!loading && visible.length === 0 && <Box sx={{ py: 8, px: 2, textAlign: 'center' }}><Inventory2OutlinedIcon sx={{ fontSize: 48, color: 'text.disabled' }} /><Typography variant="h6" fontWeight={800}>{products.length === 0 ? 'ยังไม่มีรายการขายด่วน' : 'ไม่พบรายการที่ค้นหา'}</Typography><Typography color="text.secondary" sx={{ mb: 2 }}>{products.length === 0 ? 'เพิ่มสินค้าเพื่อเริ่มใช้งานเมนูขายด่วน' : 'ลองเปลี่ยนคำค้นหาหรือตัวกรอง'}</Typography>{products.length === 0 && <Button variant="contained" startIcon={<AddRoundedIcon />} onClick={() => openEditor(null)}>เพิ่มรายการ</Button>}</Box>}
      {!loading && visible.length > 0 && <Stack direction={{ xs: 'column', sm: 'row' }} justifyContent="space-between" alignItems="center" gap={1.5} sx={{ px: 2, py: 1.5, borderTop: '1px solid', borderColor: 'divider' }}><Stack direction="row" alignItems="center" gap={1}><Typography variant="body2">แสดงต่อหน้า</Typography><Select size="small" value={rowsPerPage} onChange={e => setRowsPerPage(Number(e.target.value))}>{pageSizes.map(n => <MenuItem key={n} value={n}>{n}</MenuItem>)}</Select><Typography variant="body2" color="text.secondary">{(page - 1) * rowsPerPage + 1}–{Math.min(page * rowsPerPage, visible.length)} จาก {visible.length} รายการ</Typography></Stack><Pagination page={page} count={pageCount} onChange={(_, value) => setPage(value)} color="primary" size="small" /></Stack>}
    </Card>
  </Stack>
  <QuickSellerEditor open={editorOpen} initial={draft} editing={editing} busy={busy} onClose={() => setEditorOpen(false)} onSave={saveEditor} />
  <Dialog open={Boolean(deleteTarget)} onClose={() => !busy && setDeleteTarget(null)} maxWidth="xs" fullWidth><DialogTitle>ยืนยันการลบรายการ</DialogTitle><DialogContent><Typography>ต้องการลบ “{deleteTarget?.name}” หรือไม่? การดำเนินการนี้ไม่สามารถย้อนกลับได้</Typography></DialogContent><DialogActions><Button onClick={() => setDeleteTarget(null)} disabled={busy}>ยกเลิก</Button><Button variant="contained" color="error" onClick={() => void remove()} disabled={busy}>ลบรายการ</Button></DialogActions></Dialog>
  <Snackbar open={Boolean(notice)} autoHideDuration={2600} onClose={() => setNotice(null)} message={`✓ ${notice ?? ''}`} anchorOrigin={{ vertical: 'bottom', horizontal: 'center' }} />
  </AdminPageContainer>;
}
