export const glossyDesignTokens = {
  brand: {
    ink: '#111318',
    paper: '#F7F4ED',
    cyan: '#00A9CE',
    cyanStrong: '#007F96',
    magenta: '#DF167F',
    yellow: '#F4CF3F',
  },
  surface: {
    page: '#FBFAF6',
    card: '#FFFFFF',
    subtle: '#F7F4ED',
    raised: '#FBFAF6',
    active: '#ECE7DD',
    paperDeep: '#E8E2D8',
    hover: 'rgba(17, 19, 24, 0.04)',
    hoverWarm: 'rgba(232, 226, 216, 0.72)',
    inverse: '#111318',
  },
  text: {
    primary: '#111318',
    secondary: '#6B6D67',
    soft: '#31352F',
    inverse: '#FFFFFF',
  },
  border: {
    default: 'rgba(17, 19, 24, 0.10)',
    strong: 'rgba(17, 19, 24, 0.20)',
  },
  action: {
    primary: '#007F96',
    primarySoft: 'rgba(0, 127, 150, 0.08)',
    primaryBorder: 'rgba(0, 127, 150, 0.22)',
    focusRing: '#00A9CE',
  },
  status: {
    success: '#2E8B57',
    successSoft: '#EAF7EF',
    successBorder: '#BEE3CC',
    warning: '#C98200',
    warningSoft: '#FFF6DF',
    warningBorder: '#F2D79A',
    error: '#D14343',
    errorSoft: '#FDECEC',
    errorBorder: '#F4C3C3',
    info: '#4C6FFF',
    infoSoft: '#EEF2FF',
    infoBorder: '#CFD7FF',
  },
} as const;

export const glossyCssVariables = {
  '--glossy-brand-ink': glossyDesignTokens.brand.ink,
  '--glossy-brand-paper': glossyDesignTokens.brand.paper,
  '--glossy-brand-cyan': glossyDesignTokens.brand.cyan,
  '--glossy-action-primary': glossyDesignTokens.action.primary,
  '--glossy-surface-page': glossyDesignTokens.surface.page,
  '--glossy-surface-card': glossyDesignTokens.surface.card,
  '--glossy-surface-subtle': glossyDesignTokens.surface.subtle,
  '--glossy-text-primary': glossyDesignTokens.text.primary,
  '--glossy-text-secondary': glossyDesignTokens.text.secondary,
  '--glossy-border-default': glossyDesignTokens.border.default,
} as const;
