export const glossyDesignTokens = {
  brand: {
    ink: '#111318',
    paper: '#F7F4ED',
    cyan: '#00A9CE',
    cyanStrong: '#007F96',
    magenta: '#DF167F',
    yellow: '#F4CF3F',
  },
  surface: {
    page: '#FBFAF6',
    card: '#FFFFFF',
    subtle: '#F7F4ED',
    raised: '#FBFAF6',
    active: '#ECE7DD',
    paperDeep: '#E8E2D8',
    hover: 'rgba(17, 19, 24, 0.04)',
    hoverWarm: 'rgba(232, 226, 216, 0.72)',
    overlay: 'rgba(17, 19, 24, 0.45)',
    inverse: '#111318',
  },
  text: {
    primary: '#111318',
    secondary: '#6B6D67',
    soft: '#31352F',
    inverse: '#FFFFFF',
  },
  border: {
    default: 'rgba(17, 19, 24, 0.10)',
    strong: 'rgba(17, 19, 24, 0.20)',
  },
  action: {
    primary: '#007F96',
    primarySoft: 'rgba(0, 127, 150, 0.08)',
    primaryBorder: 'rgba(0, 127, 150, 0.22)',
    focusRing: '#00A9CE',
  },
  display: {
    shell: '#111318',
    shellDeep: '#080A0D',
    surface: 'rgba(255, 255, 255, 0.06)',
    surfaceStrong: '#1B1F24',
    border: 'rgba(255, 255, 255, 0.12)',
    textPrimary: '#FFFFFF',
    textSecondary: 'rgba(255, 255, 255, 0.72)',
    textMuted: 'rgba(255, 255, 255, 0.52)',
    cyan: '#00A9CE',
    cyanSoft: 'rgba(0, 169, 206, 0.16)',
    violet: '#7B61FF',
    violetSoft: 'rgba(123, 97, 255, 0.14)',
    success: '#67D391',
    grid: 'rgba(255, 255, 255, 0.035)',
  },
  status: {
    success: '#2E8B57',
    successSoft: '#EAF7EF',
    successBorder: '#BEE3CC',
    warning: '#C98200',
    warningSoft: '#FFF6DF',
    warningBorder: '#F2D79A',
    error: '#D14343',
    errorSoft: '#FDECEC',
    errorBorder: '#F4C3C3',
    info: '#4C6FFF',
    infoSoft: '#EEF2FF',
    infoBorder: '#CFD7FF',
  },
} as const;

export function withAlpha(hex: string, alpha: number): string {
  const normalized = hex.replace('#', '');
  if (!/^[0-9a-fA-F]{6}$/.test(normalized)) {
    throw new Error(`withAlpha expects a 6-digit hex color, received: ${hex}`);
  }

  const red = Number.parseInt(normalized.slice(0, 2), 16);
  const green = Number.parseInt(normalized.slice(2, 4), 16);
  const blue = Number.parseInt(normalized.slice(4, 6), 16);
  const boundedAlpha = Math.min(1, Math.max(0, alpha));
  return `rgba(${red}, ${green}, ${blue}, ${boundedAlpha})`;
}

export const glossyCssVariables = {
  '--glossy-brand-ink': glossyDesignTokens.brand.ink,
  '--glossy-brand-paper': glossyDesignTokens.brand.paper,
  '--glossy-brand-cyan': glossyDesignTokens.brand.cyan,
  '--glossy-brand-cyan-strong': glossyDesignTokens.brand.cyanStrong,
  '--glossy-brand-magenta': glossyDesignTokens.brand.magenta,
  '--glossy-brand-yellow': glossyDesignTokens.brand.yellow,
  '--glossy-surface-page': glossyDesignTokens.surface.page,
  '--glossy-surface-card': glossyDesignTokens.surface.card,
  '--glossy-surface-subtle': glossyDesignTokens.surface.subtle,
  '--glossy-surface-raised': glossyDesignTokens.surface.raised,
  '--glossy-surface-active': glossyDesignTokens.surface.active,
  '--glossy-surface-paper-deep': glossyDesignTokens.surface.paperDeep,
  '--glossy-surface-hover': glossyDesignTokens.surface.hover,
  '--glossy-surface-hover-warm': glossyDesignTokens.surface.hoverWarm,
  '--glossy-surface-overlay': glossyDesignTokens.surface.overlay,
  '--glossy-surface-inverse': glossyDesignTokens.surface.inverse,
  '--glossy-text-primary': glossyDesignTokens.text.primary,
  '--glossy-text-secondary': glossyDesignTokens.text.secondary,
  '--glossy-text-soft': glossyDesignTokens.text.soft,
  '--glossy-text-inverse': glossyDesignTokens.text.inverse,
  '--glossy-border-default': glossyDesignTokens.border.default,
  '--glossy-border-strong': glossyDesignTokens.border.strong,
  '--glossy-action-primary': glossyDesignTokens.action.primary,
  '--glossy-action-primary-soft': glossyDesignTokens.action.primarySoft,
  '--glossy-action-primary-border': glossyDesignTokens.action.primaryBorder,
  '--glossy-action-focus-ring': glossyDesignTokens.action.focusRing,
  '--glossy-display-shell': glossyDesignTokens.display.shell,
  '--glossy-display-shell-deep': glossyDesignTokens.display.shellDeep,
  '--glossy-display-surface': glossyDesignTokens.display.surface,
  '--glossy-display-surface-strong': glossyDesignTokens.display.surfaceStrong,
  '--glossy-display-border': glossyDesignTokens.display.border,
  '--glossy-display-text-primary': glossyDesignTokens.display.textPrimary,
  '--glossy-display-text-secondary': glossyDesignTokens.display.textSecondary,
  '--glossy-display-text-muted': glossyDesignTokens.display.textMuted,
  '--glossy-display-cyan': glossyDesignTokens.display.cyan,
  '--glossy-display-cyan-soft': glossyDesignTokens.display.cyanSoft,
  '--glossy-display-violet': glossyDesignTokens.display.violet,
  '--glossy-display-violet-soft': glossyDesignTokens.display.violetSoft,
  '--glossy-display-success': glossyDesignTokens.display.success,
  '--glossy-display-grid': glossyDesignTokens.display.grid,
  '--glossy-status-success': glossyDesignTokens.status.success,
  '--glossy-status-success-soft': glossyDesignTokens.status.successSoft,
  '--glossy-status-success-border': glossyDesignTokens.status.successBorder,
  '--glossy-status-warning': glossyDesignTokens.status.warning,
  '--glossy-status-warning-soft': glossyDesignTokens.status.warningSoft,
  '--glossy-status-warning-border': glossyDesignTokens.status.warningBorder,
  '--glossy-status-error': glossyDesignTokens.status.error,
  '--glossy-status-error-soft': glossyDesignTokens.status.errorSoft,
  '--glossy-status-error-border': glossyDesignTokens.status.errorBorder,
  '--glossy-status-info': glossyDesignTokens.status.info,
  '--glossy-status-info-soft': glossyDesignTokens.status.infoSoft,
  '--glossy-status-info-border': glossyDesignTokens.status.infoBorder,
} as const;
